set_unless[:aptFTPArchive][:suite] = "beta prod"
set_unless[:aptFTPArchive][:codename] = "prod"
set_unless[:aptFTPArchive][:architectures] = "amd64 i386 i686"
set_unless[:aptFTPArchive][:components] = "main ops 3ppours 3pp"
set_unless[:aptFTPArchive][:archivedir] = "/var/drepo/inmobi"
set_unless[:aptFTPArchive][:aptRootPath] = "/var/drepo"
